platform :ios, '10.3'
inhibit_all_warnings!



abstract_target 'Shared' do
  use_frameworks!

  pod 'Alamofire', '~> 5.2'
  pod 'PromiseKit', '~> 6.8'
  
  
  target 'SpotImCore'
  
  abstract_target 'DemoApps' do
    pod 'SnapKit', '~> 4.2.0'
    pod 'Cards'
    pod 'Kingfisher'

    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Google-Mobile-Ads-SDK', '= 7.67'
    
    pod 'Reveal-SDK', :configurations => ['Debug'] # dependency only on debug/release build

    target 'Spot-IM.Development'
    target 'YentSpot'
    target 'DailyCaller'
    target 'Focus.de'
    target 'MarketWatch'
  end

end

post_install do |installer|
  fix_deployment_target(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
    end
  end
end

def fix_deployment_target(installer)
  return if !installer
  project = installer.pods_project
  project_deployment_target = project.build_configurations.first.build_settings['IPHONEOS_DEPLOYMENT_TARGET']

  puts "Make sure all pods deployment target is #{project_deployment_target.green}"
  project.targets.each do |target|
    puts "  #{target.name}".blue
    target.build_configurations.each do |config|
      old_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      new_target = project_deployment_target
      next if old_target == new_target
      puts "    #{config.name}: #{old_target.yellow} -> #{new_target.green}"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = new_target
    end
  end
end
