platform :ios, '9.0'
inhibit_all_warnings!

target 'Spot-IM.Development' do
  use_frameworks!

  pod 'Alamofire', '~> 4.8.2'
  pod 'SnapKit', '~> 4.2.0'
  # Pods for Spot-IM.Development
  
  pod 'Cards'
  pod 'Kingfisher'
  
  pod 'Firebase/Analytics'
  pod 'Fabric'
  pod 'Crashlytics'
  
  pod 'Reveal-SDK', :configurations => ['Debug']
  
  target 'Spot-IM.DevelopmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
