platform :ios, '9.0'
inhibit_all_warnings!

project 'Spot-IM.Development.xcodeproj', {
  'Debug' => :debug,
  'DebugWithAds' => :debug,
}

ads_configurations = ['ReleaseWithAds', 'DebugWithAds']
debug_configurations = ['Debug', 'DebugWithAds']

abstract_target 'Shared' do
  use_frameworks!
  
  pod 'Alamofire', '~> 4.8.2'
  
  target 'Spot-IM.Development' do
    
    pod 'SnapKit', '~> 4.2.0'
    pod 'Cards'
    pod 'Kingfisher'
    
    pod 'Fabric'
    pod 'Crashlytics'
    
    pod 'Reveal-SDK', :configurations => debug_configurations
    
  end

  target 'YentSpot' do

    pod 'SnapKit', '~> 4.2.0'
    pod 'Cards'
    pod 'Kingfisher'

    pod 'Fabric'
    pod 'Crashlytics'

    pod 'Reveal-SDK', :configurations => debug_configurations

  end
  
  target 'SpotImCore' do
    
    pod 'SwiftLint', '~> 0.34.0', :configurations => debug_configurations
    
    # Pods for configurations with google ads
    
    pod 'nanopb', '= 0.3.901', :configurations => ads_configurations
    pod 'GoogleAppMeasurement', '= 6.1.3', :configurations => ads_configurations
    pod 'GoogleUtilities', '= 6.3.1', :configurations => ads_configurations
    pod 'Google-Mobile-Ads-SDK', '= 7.51.0', :configurations => ads_configurations
    
  end
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == 'Alamofire'
          target.build_configurations.each do |config|
              config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
          end
      end
  end
end
