# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "dmjq-rohv-jwmk-fcxi"
ENV["MATCH_PASSWORD"] = "iOSOpenwebPrivateKeydfdskdfnlwqijeakpnqs"

default_platform(:ios)

git_url = "git@github.com:SpotIM/openweb-ios-certs.git"

platform :ios do
  desc "Push a new beta build to TestFlight"
  
  lane :beta do
    match(type: "appstore")
    increment_build_number(build_number: Time.now.to_i.to_s[0..7])
    build_app(workspace: "Spot-IM.Development.xcworkspace", scheme: "Spot-IM.Development")
    upload_to_testflight
  end

  lane :release_pod do |options|
    increment_build_number()
    increment_version_number(version_number: options[:version]) # Set a specific version number)
    xcodebuild(
      scheme: "Package SpotImCoreSDK",
      configuration: "Release",
      destination: "generic/platform=iOS",
      clean: true,
      build: true
    )
  end

  lane :prepare_demo_app do
    match(type: "appstore", readonly: true)
    increment_build_number_in_xcodeproj

    build_app(workspace: "Spot-IM.Development.xcworkspace", 
      scheme: "Spot-IM.Development", 
      export_options: {
        method: "app-store",
        provisioningProfiles: { 
            "im.spot.demo" => "match AppStore im.spot.demo"
        }
    })
  end

  lane :bump_version do
    increment_version_number_in_xcodeproj(
      bump_type: 'patch',
      scheme: 'Spot-IM.Development'
    )
    increment_build_number_in_xcodeproj
  end
end
