platform :ios, '12.0'
inhibit_all_warnings!
use_frameworks!

workspace 'OpenWeb-Development'
project 'OpenWeb-Development.xcodeproj'
project 'OpenWeb-SampleApp/OpenWeb-SampleApp.xcodeproj'

def rx_pods
  pod 'RxSwift', '6.7.0'
  pod 'RxRelay', '6.7.0'
  pod 'RxCocoa', '6.7.0'
end

target 'OpenWeb-SampleApp' do
  project 'OpenWeb-SampleApp/OpenWeb-SampleApp.xcodeproj'
  pod 'SnapKit', '~> 5.7.1'
  pod 'Google-Mobile-Ads-SDK', '= 8.0'
  pod 'Alamofire', '~> 5.10.1'
  rx_pods
end

target 'OpenWebSDK' do
  project 'OpenWeb-Development.xcodeproj'
  rx_pods
end

target 'OpenWebSDKTests' do
  project 'OpenWeb-Development.xcodeproj'
  pod 'Quick', '~> 5.0.1'
  pod 'Nimble', '~> 10.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
