platform :ios, '9.0'
source 'git@github.com:SpotIM/spotim-ios-sdk-pod.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'Spot.IM-Example.Pods' do
  use_frameworks!

  # Pods for Spot.IM-Example.Pods
  pod 'Spot.IM-Core'

  target 'Spot.IM-Example.PodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |lib|
    lib.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        end
    end
end