disabled_rules: # rule identifiers to exclude from running
  - closing_brace
  - closure_parameter_position
  - comment_spacing
  - compiler_protocol_init
  - computed_accessors_order

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - ../Pods
  - ../fastlane
  - ../Spot-IM.DevelopmentTests

included: # paths to include during linting. `excluded` paths are still ignored.
  - ../Spot-IM.Development

opt_in_rules: # some rules are only opt-in
  - empty_count
  - unused_declaration
