name: Release Sample App
run-name: Release Sample App

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: Version Number
        required: true

      build_number:
        description: Build Number
        required: true
        default: '0'

      scheme:
         description: Scheme
         type: choice
         required: true
         options:
           - "app"
           - "beta_app"
           - "public_app"

jobs:
  release-app:
    name: ${{github.actor}} release sample app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Validate version
        run: |
          VERSION="${{ inputs.version_number }}"
          rx='^([0-9]+\.){2}(\*|[0-9]+)(-.*)?$'
          if [[ $VERSION =~ $rx ]]; then
            echo "INFO: Version - $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "ERROR: Unable to validate version: '$VERSION'"
            exit 1
          fi

      - name: Put Branch in env
        run: |
          BRANCH="test/${{ inputs.scheme }}/${{ env.VERSION }}"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          
      - name: Push Branch
        run: |
          if git ls-remote --exit-code --heads origin "${{ env.BRANCH }}"
          then
              echo "REMOTE BRANCH EXISTS"
              git push origin --delete "${{ env.BRANCH }}"
          else
            echo "REMOTE BRANCH NOT FOUND"
          fi
          git checkout -b "${{ env.BRANCH }}"
          git push --set-upstream origin "${{ env.BRANCH }}"
          
